-- =========================================================
-- Exact allocation optimizer configuration and job queue
-- =========================================================

insert into public.app_settings (key, value)
values (
  'allocation_optimizer_config',
  jsonb_build_object(
    'capacity', 45,
    'price', 0,
    'recommended_minimum_passengers', 36
  )
)
on conflict (key) do nothing;

create table if not exists public.allocation_optimization_jobs (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'PENDING'
    check (
      status in (
        'PENDING',
        'RUNNING',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'OPTIMAL',
        'INFEASIBLE',
        'FAILED'
      )
    ),
  requested_by uuid not null,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  cancel_requested_at timestamptz,
  input_hash text not null,
  input_snapshot jsonb not null,
  progress integer not null default 0 check (progress between 0 and 100),
  current_phase text,
  elapsed_seconds integer not null default 0 check (elapsed_seconds >= 0),
  best_known_bus_count integer check (best_known_bus_count >= 0),
  proven_bus_count integer check (proven_bus_count >= 0),
  result jsonb,
  diagnostics jsonb,
  error_message text,
  worker_id text,
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_allocation_optimization_one_active_job
  on public.allocation_optimization_jobs ((true))
  where status in ('PENDING', 'RUNNING', 'CANCEL_REQUESTED');

create index if not exists idx_allocation_optimization_jobs_requested
  on public.allocation_optimization_jobs (requested_at desc);

create table if not exists public.allocation_optimization_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null
    references public.allocation_optimization_jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null,
  detail jsonb not null default '{}'::jsonb
);

create index if not exists idx_allocation_optimization_events_job_created
  on public.allocation_optimization_events(job_id, created_at);

alter table public.allocation_optimization_jobs enable row level security;
alter table public.allocation_optimization_events enable row level security;

revoke all on table public.allocation_optimization_jobs
  from public, anon, authenticated;
revoke all on table public.allocation_optimization_events
  from public, anon, authenticated;

create or replace function public.set_allocation_optimization_job_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_allocation_optimization_job_updated_at
  on public.allocation_optimization_jobs;
create trigger set_allocation_optimization_job_updated_at
before update on public.allocation_optimization_jobs
for each row execute function public.set_allocation_optimization_job_updated_at();

revoke all on function public.set_allocation_optimization_job_updated_at()
  from public, anon, authenticated;

create or replace function public.get_allocation_optimizer_config()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_config jsonb;
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can view allocation optimizer configuration.';
  end if;

  select value
  into v_config
  from public.app_settings
  where key = 'allocation_optimizer_config';

  return coalesce(
    v_config,
    jsonb_build_object(
      'capacity', 45,
      'price', 0,
      'recommended_minimum_passengers', 36
    )
  );
end;
$$;

create or replace function public.save_allocation_optimizer_config(
  p_capacity integer,
  p_price integer,
  p_recommended_minimum_passengers integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can update allocation optimizer configuration.';
  end if;
  if p_capacity <= 0 then
    raise exception 'Bus capacity must be positive.';
  end if;
  if p_price < 0 then
    raise exception 'Bus price cannot be negative.';
  end if;
  if p_recommended_minimum_passengers <= 0
    or p_recommended_minimum_passengers > p_capacity then
    raise exception 'Recommended minimum passengers must be between 1 and capacity.';
  end if;
  if exists (
    select 1
    from public.allocation_optimization_jobs
    where status in ('PENDING', 'RUNNING', 'CANCEL_REQUESTED')
  ) then
    raise exception 'Allocation optimizer configuration cannot change during an active job.';
  end if;

  v_config := jsonb_build_object(
    'capacity', p_capacity,
    'price', p_price,
    'recommended_minimum_passengers', p_recommended_minimum_passengers
  );

  insert into public.app_settings (key, value)
  values ('allocation_optimizer_config', v_config)
  on conflict (key) do update
  set value = excluded.value;

  return v_config;
end;
$$;

create or replace function public.create_allocation_optimization_job()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job_id uuid;
  v_config jsonb;
  v_passengers jsonb;
  v_snapshot jsonb;
  v_invalid_reservations text;
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can create allocation optimization jobs.';
  end if;
  if exists (
    select 1
    from public.allocation_optimization_jobs
    where status in ('PENDING', 'RUNNING', 'CANCEL_REQUESTED')
  ) then
    raise exception 'Another allocation optimization job is already active.';
  end if;

  v_config := public.get_allocation_optimizer_config();
  if coalesce((v_config ->> 'capacity')::integer, 0) <= 0
    or coalesce((v_config ->> 'price')::integer, -1) < 0
    or coalesce((v_config ->> 'recommended_minimum_passengers')::integer, 0) <= 0 then
    raise exception 'Allocation optimizer configuration is invalid.';
  end if;

  with active_reservations as (
    select
      reservation.id,
      coalesce(nullif(reservation.data ->> 'campus', ''), nullif(reservation.campus, '')) as campus,
      coalesce(nullif(reservation.data ->> 'team', ''), nullif(reservation.team, '')) as team,
      case
        when jsonb_typeof(reservation.data -> 'stationPreferences') = 'array'
          then reservation.data -> 'stationPreferences'
        else coalesce(reservation.station_preferences, '[]'::jsonb)
      end as preferences
    from public.reservations reservation
    where reservation.status is distinct from 'cancelled'
  ),
  normalized as (
    select
      active.id,
      active.campus,
      active.team,
      active.preferences,
      active.preferences #>> '{0,station,name}' as first_choice,
      active.preferences #>> '{1,station,name}' as second_choice
    from active_reservations active
  )
  select string_agg(normalized.id::text, ', ' order by normalized.id::text)
  into v_invalid_reservations
  from normalized
  where normalized.campus is null
    or normalized.team is null
    or jsonb_typeof(normalized.preferences) <> 'array'
    or case
      when jsonb_typeof(normalized.preferences) = 'array'
        then jsonb_array_length(normalized.preferences) <> 2
      else true
    end
    or nullif(normalized.first_choice, '') is null
    or nullif(normalized.second_choice, '') is null
    or normalized.first_choice = normalized.second_choice;

  if v_invalid_reservations is not null then
    raise exception 'Active reservations have invalid allocation data: %',
      v_invalid_reservations;
  end if;

  with active_reservations as (
    select
      reservation.id,
      coalesce(nullif(reservation.data ->> 'campus', ''), reservation.campus, '-') as campus,
      coalesce(nullif(reservation.data ->> 'team', ''), reservation.team, '-') as team,
      case
        when jsonb_typeof(reservation.data -> 'stationPreferences') = 'array'
          then reservation.data -> 'stationPreferences'
        else coalesce(reservation.station_preferences, '[]'::jsonb)
      end as preferences,
      reservation.created_at
    from public.reservations reservation
    where reservation.status is distinct from 'cancelled'
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'reservation_id', active.id::text,
        'campus', active.campus,
        'team', active.team,
        'first_choice', active.preferences #>> '{0,station,name}',
        'second_choice', active.preferences #>> '{1,station,name}'
      )
      order by active.created_at, active.id
    ),
    '[]'::jsonb
  )
  into v_passengers
  from active_reservations active;

  if jsonb_array_length(v_passengers) = 0 then
    raise exception 'No active reservations are available for optimization.';
  end if;

  v_snapshot := jsonb_build_object(
    'schema_version', 1,
    'bus', v_config,
    'passengers', v_passengers
  );

  begin
    insert into public.allocation_optimization_jobs (
      status,
      requested_by,
      input_hash,
      input_snapshot
    )
    values (
      'PENDING',
      auth.uid(),
      md5(v_snapshot::text),
      v_snapshot
    )
    returning id into v_job_id;
  exception
    when unique_violation then
      raise exception 'Another allocation optimization job is already active.';
  end;

  insert into public.allocation_optimization_events (job_id, event_type, detail)
  values (
    v_job_id,
    'JOB_CREATED',
    jsonb_build_object(
      'requested_by', auth.uid()::text,
      'passenger_count', jsonb_array_length(v_passengers),
      'input_hash', md5(v_snapshot::text)
    )
  );

  return v_job_id;
exception
  when invalid_text_representation or numeric_value_out_of_range then
    raise exception 'Allocation optimizer configuration contains invalid numbers.';
end;
$$;

create or replace function public.get_allocation_optimization_job(
  p_job_id uuid
)
returns table (
  id uuid,
  status text,
  requested_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  progress integer,
  current_phase text,
  elapsed_seconds integer,
  best_known_bus_count integer,
  proven_bus_count integer,
  result jsonb,
  diagnostics jsonb,
  error_message text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can view allocation optimization jobs.';
  end if;

  return query
  select
    job.id,
    job.status,
    job.requested_at,
    job.started_at,
    job.completed_at,
    job.progress,
    job.current_phase,
    job.elapsed_seconds,
    job.best_known_bus_count,
    job.proven_bus_count,
    job.result,
    job.diagnostics,
    job.error_message
  from public.allocation_optimization_jobs job
  where job.id = p_job_id;
end;
$$;

create or replace function public.get_recent_allocation_optimization_jobs(
  p_limit integer default 20
)
returns table (
  id uuid,
  status text,
  requested_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  progress integer,
  current_phase text,
  elapsed_seconds integer,
  best_known_bus_count integer,
  proven_bus_count integer,
  error_message text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can view allocation optimization jobs.';
  end if;

  return query
  select
    job.id,
    job.status,
    job.requested_at,
    job.started_at,
    job.completed_at,
    job.progress,
    job.current_phase,
    job.elapsed_seconds,
    job.best_known_bus_count,
    job.proven_bus_count,
    job.error_message
  from public.allocation_optimization_jobs job
  order by job.requested_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 100);
end;
$$;

create or replace function public.cancel_allocation_optimization_job(
  p_job_id uuid
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if auth.uid() is null or not public.is_global_admin() then
    raise exception 'Only global admins can cancel allocation optimization jobs.';
  end if;

  update public.allocation_optimization_jobs job
  set
    status = case
      when job.status = 'PENDING' then 'CANCELLED'
      when job.status = 'RUNNING' then 'CANCEL_REQUESTED'
      else job.status
    end,
    cancel_requested_at = case
      when job.status in ('PENDING', 'RUNNING') then now()
      else job.cancel_requested_at
    end,
    completed_at = case
      when job.status = 'PENDING' then now()
      else job.completed_at
    end
  where job.id = p_job_id
  returning status into v_status;

  if v_status is null then
    raise exception 'Allocation optimization job not found.';
  end if;

  insert into public.allocation_optimization_events (job_id, event_type, detail)
  values (
    p_job_id,
    'CANCEL_REQUESTED',
    jsonb_build_object('requested_by', auth.uid()::text, 'next_status', v_status)
  );

  return v_status;
end;
$$;

revoke all on function public.get_allocation_optimizer_config()
  from public, anon;
revoke all on function public.save_allocation_optimizer_config(integer, integer, integer)
  from public, anon;
revoke all on function public.create_allocation_optimization_job()
  from public, anon;
revoke all on function public.get_allocation_optimization_job(uuid)
  from public, anon;
revoke all on function public.get_recent_allocation_optimization_jobs(integer)
  from public, anon;
revoke all on function public.cancel_allocation_optimization_job(uuid)
  from public, anon;

grant execute on function public.get_allocation_optimizer_config()
  to authenticated;
grant execute on function public.save_allocation_optimizer_config(integer, integer, integer)
  to authenticated;
grant execute on function public.create_allocation_optimization_job()
  to authenticated;
grant execute on function public.get_allocation_optimization_job(uuid)
  to authenticated;
grant execute on function public.get_recent_allocation_optimization_jobs(integer)
  to authenticated;
grant execute on function public.cancel_allocation_optimization_job(uuid)
  to authenticated;

notify pgrst, 'reload schema';
